spring:
  config:
    import: file:.env[.properties]
  datasource:
    url: jdbc:h2:mem:parkingdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

  security:
    oauth2:
      client:
        registration:
          cognito:
            clientId: ${aws.cognito.clientId}
            client-secret: ${aws.cognito.clientSecret}
            scope: openid
            redirect-uri: ${aws.cognito.redirect-uri}
            clientName: ${aws.cognito.client-name}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
        provider:
          cognito:
            issuerUri: https://cognito-idp.us-east-1.amazonaws.com/${aws.cognito.client-code}
            user-name-attribute: cognito:username
            token-uri: https://${aws.cognito.client-domain}.auth.us-east-1.amazoncognito.com/oauth2/token
            authorization-uri: https://${aws.cognito.client-domain}.auth.us-east-1.amazoncognito.com/oauth2/authorize
      resourceserver:
        jwt:
          issuerUri: https://cognito-idp.us-east-1.amazonaws.com/${aws.cognito.client-code}
          jwk-set-uri: https://cognito-idp.us-east-1.amazonaws.com/${aws.cognito.client-code}/.well-known/jwks.json

aws:
  cognito:
    clientId: ${COGNITO-CLIENT-ID}
    clientSecret: ${COGNITO-CLIENT-SECRET}
    client-code: ${COGNITO-CLIENT-CODE}
    client-domain: ${COGNITO-CLIENT-DOMAIN}
    client-name: ${COGNITO-CLIENT-NAME}
    redirect-uri: ${COGNITO-CLIENT-REDIRECT-URI}

bucket:
  capacity: ${BUCKET-CAPACITY}
  token-size: ${BUCKET-TOKEN-SIZE}
  refill-interval: ${BUCKET-REFILL-INTERVAL}

parking:
  lot-size: ${PARKING-LOT-SIZE}

server:
  port: ${PORT}
